export class Languages {
  public RU_LANGUAGE = {
    firstname: 'Санжар',
    lastname: 'Дадаханов',
    nameapp: 'E-Order',
    language: 'язык',
    russian: 'Русский',
    english: 'Английский',
    main: 'Главная',
    order: 'Заказ',
    admin: 'Админ',
    registration: 'Регистрация',
    login: 'Войти',
    abouttext: 'Вы можотете тут заказывать еду не вызывая официанта, или заранее забранировать место',
    successadded: 'Успешно добавлено',
    successupdated: 'Успешно добавлено',
    successbooked: 'Успешно забронирован',
    alreadyadded: 'Уже добавлено',
    empty: 'empty',
    full: 'full',
    update: 'Update',
    username: 'Номер пользователя',
    role: "Роль",
    submit: " Отправить",
    fullname: "ФИО",
    productname: "Наименование Автобуса для туров",
    productprice: "Цена автобуса для туров",
    title: "Название",
    category: "Категория",
    date: "Дата",
    food: "Транспорт",
    available: "Доступен",
    notavailable: "Не доступен",
    tablename: "Номер месты",
    tableexist: "Существующие места",
    tablechangename: "Изменение номер места",
    tableavailable: "Доступность месты",
    urlfooditem: "food-item",
    urlcustomer: "customer",
    urltable: "table",
    urlmenuday: "menu-day",
    productadd: "Добавить Автобусов",
    customeraddrole: "Добавить пользователям роль",
    tableedit: "Изменить место в Автобусе",
    menudayadd: "Добавить Расписание дня",
    responsefromserver: "Ответ от сервера",
    waitresponse: "Ждите ответа",
    placetaken: "Место занято",
    close: "Закрыть",
    exit: "Выйти",
    numberofpeople: "Количество людей",
    reservationday: "День бронирования",
    reservationtimefrom: "Время бронирования с:",
    fromwhere: "Откуда",
    whereto:"Куда",
    datetoreserv:"Дата бронирования",
    firstnameclient:"Имя",
    surnameclient: "Фамилия",
    reservationtimeto: "Время бронирования до:",
    numberoftelephone: "Номер телефона",
    reservationtable: "Бронирования места:",
    diploma: "diploma",
    loadingwait: "Загрузка, ждите...",
    button: "Войти",
    beforebooking: "Предазаказ",
    orderfooditem: "Заказ транспорта",
    booking: "Бронирование",
    canbookingplace: "Для того чтобы подтвердить бронь нажимайте на кнопку Бронировать",
    scheduletext: "Расписание",
    orderno: "Номер заказа",
    customer: "Пользователь",
    pmethod: "Способ оплаты",
    gtotal: "Общий счет",
    createnew: " Создать новый",
    fooditem: "Транспорт",
    select: "Выбор",
    price: "Цена",
    quantity: "Количество",
    total: "Всего",
    submitsuccesfully: "Успешно отправлено",
    cash: "Cash",
    card: "Сard",
    granttotal: "Общий счет",
    paymentmethod: "Cпособ оплаты",
    nofooditemselectd: "Для этого заказа не выбран ни один транспорт.",
    stillorder: "Eще заказывают:",
    withthisproduct: "C этим продуктом",
    about: "О нас",
    account: 'Аккаунт:',
    status: 'Статус',
    acceptfood: 'Принято',
    telegrambot: 'Телеграм',
    recorddateday: "Забронированный день",
    listorders: "Заказы",
    contactus: "Контакты",
    aboutus: "О нас",
    instruction: "Инструкция",
    choosetable: "Выбрать место",
    address: "Богенбай батыра 63, Алматы, КЗ",
    contactustext: "Расскажите нам о своем опыте бронирования! Если у вас есть идеи о том, как мы можем улучшить, мы будем рады услышать от вас. Отправьте нам свой отзыв, заполнив онлайн-запрос внизу страницы, и мы его получим!",
    monday: "Понедельник",
    friday: "Пятница",
    saturday: "Суббота",
    sunday: "Воскресенье",
    goodmorning: "с 9.00 до 24.00",
    launch: "c 9.00 до 22.00",
    evening: "c 10.00 до 24.00",
    openhours: "Время работы",
    officeadresss: "Адрес офиса",
    yourname: 'Ваше имя',
    emailaddress: 'Адресс электронной почты',
    subject: 'Тема',
    typeyourmessage: 'Введите ваше сообщение',
    sendmessage: 'Отправить сообщение',
    message: 'Сообщение',
    email: 'Адрес',
    justname: 'Имя',
    enterin: " Вошли как",
    createdsuccess: "Успешно создан аккаунт! \nТеперь можете войти под своим аккаунтом",
    createdsuccessfail: "Уже зарегестрирова номер. Выберите другой номер.",
    reserved: 'Все права защищены',
    copyright: 'Авторское право 2021',
    anonymous: 'аноним',
    categorytype: 'категории транспортов',


    abouttext1: 'В приложении можно быстро и удобно бронировать билеты или заказать тарнспортов на поездку с компанией',
    abouttext2: 'Ключ к нашему успеху прост: мы предлагаем высококачественные транспорты, которые всегда поможет в турах с компанией.\n' +
    '                Мы гордимся тем, что предлагаем нашим клиентам комфортный транспорт для путешествии межгород или внутри города, например: Комфортабельный Volvo 9700.',
    abouttext3: 'Наслаждайтесь поездками на природу. Выберите лучший транспорт. Но, прежде всего, расслабьтесь!\n' +
    '                Мы хотели бы поблагодарить Вас за постоянную поддержку.',


    accept: 'Принять',
    acceptend: 'Завершить',
    acceptended: 'Завершено',
    password: 'Пароль пользователя',
    recepientusername: 'Пароль получателя',
    pending: 'В ожидании',
    process: 'В процессе',
    completed: 'Завершено',
    productcategory: "Наименование категории",
    productdescription: "Описание транспорта",


    contactmessageemtpty: "Некоторые поля пусты",
    contactmessagefull: "Успешно доставлено, спасибо за ваше внимание",
    bookingInvalid: "Неправильно заполнены поля",

  };
  public EN_LANGUAGE = {
    firstname: 'Sanzhar',
    lastname: 'Dadakhanov',
    name: 'Booking app.',
    language: 'Language',
    russian: 'Russian',
    english: 'English',
    main: 'Main',
    order: 'Order',
    admin: 'Admin',
    registration: 'Registration',
    login: 'Login',
    productadd: "Add product",
    customeraddrole: "Add customer",
    tableedit: "Edit table",
    menudayadd: "Add menu-day",
    numberofpeople: "Number of people:",
    reservationday: "Reservation day:",
    reservationtimefrom: "Reservation time from:",
    fromwhere: "From",
    whereto:"To",
    datetoreserv:"Date reservation",
    firstnameclient:"Firtname",
    surnameclient: "Surname",
    reservationtimeto: "Reservation time to:",
    numberoftelephone: "Number of telephone",
    reservationtable: "Reservation table:",
    diploma: "Diploma",
    orderfooditem: "Order food item",
    orderno: "Order no.",
    customer: "Customer",
    pmethod: "Pay method",
    gtotal: "Total",
    granttotal: "Grand total",
    createnew: "Create new",
    fooditem: "Transport item",
    quantity: "Quantity",
    total: "Total",
    submitsuccesfully: "Submitted successfully",
    cash: "Cash",
    card: "Card",
    food: "Transport",
    paymentmethod: "Payment method",
    nofooditemselectd: " No food item selected for this order.",

    abouttext: 'You can order food here without calling the waiter, or pre-book a place in advance',
    successadded: 'Successfully added',
    successupdated: 'Successfully updated',
    successbooked: 'Successfully booked',
    alreadyadded: 'Already added',
    empty: 'empty',
    full: 'full',
    update: 'update',
    username: 'Username\'s number',
    role: "Role",
    submit: " Submit",
    fullname: "Full name",
    productname: "Bus name for travel",
    productprice: "Bus price for travel",
    title: "Name",
    category: "Category",
    date: "Date",
    available: "Available",
    notavailable: "Not available",
    tablename: "Number of place",
    tableexist: "Table exist",
    tablechangename: "Add new place ",
    tableavailable: "Change place availabe",
    urlfooditem: "food-item",
    urlcustomer: "customer",
    urltable: "table",
    urlmenuday: "menu-day",
    responsefromserver: "Response from server",
    waitresponse: "Waiting answer",
    placetaken: "Place is taken",
    close: "Close",
    exit: "Exit",
    loadingwait: "Loading, wait...",
    button: "Login",
    beforebooking: "Pre-order",
    booking: "Booking",
    canbookingplace: "To confirm your reservation, click on the Book button",
    scheduletext: "Schedule",
    select: "Select",
    price: "Price",
    stillorder: "still order:",
    withthisproduct: "With this product",
    about: "About us",
    nameapp: 'E-Order',
    account: 'Account:',
    status: 'Status',
    acceptfood: 'Accept',
    telegrambot: 'Telegram',
    recorddateday: "Booked day",
    listorders: "Orders",
    contactus: "Contact us",
    instruction: "Instruction",
    choosetable: "Choose place",
    contactustext: "Tell us about your booking experience! If you have ideas on how we can improve we'd love to hear from you. Send us your feedback by completing the online enquiry at the bottom of the page and we'll get on it!",
    aboutus: "About us",
    address: "Bogenbay Batyr 63, Almaty, KZ",
    monday: "Monday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    openhours: "Open hours",
    officeadresss: "Office adress",
    yourname: 'Your name',
    emailaddress: 'Email address',
    email: 'Email',
    subject: 'Subject',
    typeyourmessage: 'Type your message',
    message: 'Message',
    sendmessage: 'Send message',
    justname: 'Name',
    enterin: " Logged in as",

    abouttext1: 'In the application, you can quickly and conveniently book tickets or order transport for a trip with the company',
    abouttext2: 'TThe key to our success is simple: we offer high quality transports that will always help on tours with the company.\n'+
      '             We are proud to offer our customers comfortable transport for intercity or intracity travel, for example: Comfortable Volvo 9700.',
    abouttext3: 'Enjoy nature trips. Choose the best transport. But above all, relax! We would like to thank you for your continued support.',
    goodmorning: "9.00 am to 12 pm",
    launch: "9.00 am to 10 pm",
    evening: "10.00 am to 12 pm",

    password: 'Password',

    accept: 'Accept',
    acceptend: 'Complete',
    acceptended: 'Completed',
    recepientusername: 'Пароль получателя',
    pending: 'Pending',
    process: 'In the process',
    completed: 'Completed',
    reserved: 'All right reserved',
    copyright: 'Copyright 2021 ',
    createdsuccess: "Successfully created an account! \nNow you can log in with your account",
    createdsuccessfail: "Already registered number. Choose another number.",
    anonymous: 'anonymous',
    categorytype: 'Category of transport',
    productcategory: "Product category",
    productdescription: "Description of the dish",
    contactmessageemtpty: "Some fields are empty",
    contactmessagefull: "Successfully delivered, thank you for your attention.",
    bookingInvalid: "Incorrectly filled fields",


  }
}
